language: node_js
node_js:
  - "8"
install: npm install
script:
  - npm test
# before_install: npm install -g greenkeeper-lockfile@1
# before_script: greenkeeper-lockfile-update
# after_script: greenkeeper-lockfile-upload
