language: node_js

node_js:
  - "10.8"

addons:
  apt:
    packages:
      - libgconf-2-4
  artifacts:
    debug: true
    paths:
      - /home/travis/build/SparkPost/matchbox/cypress/videos/

cache:
    # Caching node modules and Cypress binary to speed up build
    directories:
      - ~/.npm
      - ~/.cache

script:
  - npm --version
  - npm run test:ci
