export default [
  {
    "category": "background-color",
    "css": "--color-brand-orange",
    "friendly": "Color Brand Orange",
    "javascript": "color_brand_orange",
    "name": "color-brand-orange",
    "scss": "color(brand, orange)",
    "type": "color",
    "value": "#fa6423"
  },
  {
    "category": "background-color",
    "css": "--color-brand-gray",
    "friendly": "Color Brand Gray",
    "javascript": "color_brand_gray",
    "name": "color-brand-gray",
    "scss": "color(brand, gray)",
    "type": "color",
    "value": "#55555a"
  },
  {
    "category": "background-color",
    "css": "--color-brand-blue",
    "friendly": "Color Brand Blue",
    "javascript": "color_brand_blue",
    "name": "color-brand-blue",
    "scss": "color(brand, blue)",
    "type": "color",
    "value": "#37aadc"
  },
  {
    "category": "background-color",
    "css": "--color-yellow-1000",
    "friendly": "Color Yellow 1000",
    "javascript": "color_yellow_1000",
    "name": "color-yellow-1000",
    "scss": "color(yellow, 1000)",
    "type": "color",
    "value": "#3d3121"
  },
  {
    "category": "background-color",
    "css": "--color-yellow-900",
    "friendly": "Color Yellow 900",
    "javascript": "color_yellow_900",
    "name": "color-yellow-900",
    "scss": "color(yellow, 900)",
    "type": "color",
    "value": "#523e21"
  },
  {
    "category": "background-color",
    "css": "--color-yellow-800",
    "friendly": "Color Yellow 800",
    "javascript": "color_yellow_800",
    "name": "color-yellow-800",
    "scss": "color(yellow, 800)",
    "type": "color",
    "value": "#614d27"
  },
  {
    "category": "background-color",
    "css": "--color-yellow-700",
    "friendly": "Color Yellow 700",
    "javascript": "color_yellow_700",
    "name": "color-yellow-700",
    "scss": "color(yellow, 700)",
    "type": "color",
    "value": "#876a2f"
  },
  {
    "category": "background-color",
    "css": "--color-yellow-600",
    "friendly": "Color Yellow 600",
    "javascript": "color_yellow_600",
    "name": "color-yellow-600",
    "scss": "color(yellow, 600)",
    "type": "color",
    "value": "#b58c12"
  },
  {
    "category": "background-color",
    "css": "--color-yellow-500",
    "friendly": "Color Yellow 500",
    "javascript": "color_yellow_500",
    "name": "color-yellow-500",
    "scss": "color(yellow, 500)",
    "type": "color",
    "value": "#e3ad0b"
  },
  {
    "category": "background-color",
    "css": "--color-yellow-400",
    "friendly": "Color Yellow 400",
    "javascript": "color_yellow_400",
    "name": "color-yellow-400",
    "scss": "color(yellow, 400)",
    "type": "color",
    "value": "#ffda00"
  },
  {
    "category": "background-color",
    "css": "--color-yellow-300",
    "friendly": "Color Yellow 300",
    "javascript": "color_yellow_300",
    "name": "color-yellow-300",
    "scss": "color(yellow, 300)",
    "type": "color",
    "value": "#ffe75c"
  },
  {
    "category": "background-color",
    "css": "--color-yellow-200",
    "friendly": "Color Yellow 200",
    "javascript": "color_yellow_200",
    "name": "color-yellow-200",
    "scss": "color(yellow, 200)",
    "type": "color",
    "value": "#fff4b5"
  },
  {
    "category": "background-color",
    "css": "--color-yellow-100",
    "friendly": "Color Yellow 100",
    "javascript": "color_yellow_100",
    "name": "color-yellow-100",
    "scss": "color(yellow, 100)",
    "type": "color",
    "value": "#fffadb"
  },
  {
    "category": "background-color",
    "css": "--color-yellow-base",
    "friendly": "Color Yellow",
    "javascript": "color_yellow",
    "name": "color-yellow-base",
    "scss": "color(yellow)",
    "type": "color",
    "value": "#ffda00"
  },
  {
    "category": "background-color",
    "css": "--color-green-1000",
    "friendly": "Color Green 1000",
    "javascript": "color_green_1000",
    "name": "color-green-1000",
    "scss": "color(green, 1000)",
    "type": "color",
    "value": "#233b33"
  },
  {
    "category": "background-color",
    "css": "--color-green-900",
    "friendly": "Color Green 900",
    "javascript": "color_green_900",
    "name": "color-green-900",
    "scss": "color(green, 900)",
    "type": "color",
    "value": "#1b5441"
  },
  {
    "category": "background-color",
    "css": "--color-green-800",
    "friendly": "Color Green 800",
    "javascript": "color_green_800",
    "name": "color-green-800",
    "scss": "color(green, 800)",
    "type": "color",
    "value": "#067852"
  },
  {
    "category": "background-color",
    "css": "--color-green-700",
    "friendly": "Color Green 700",
    "javascript": "color_green_700",
    "name": "color-green-700",
    "scss": "color(green, 700)",
    "type": "color",
    "value": "#009f6a"
  },
  {
    "category": "background-color",
    "css": "--color-green-600",
    "friendly": "Color Green 600",
    "javascript": "color_green_600",
    "name": "color-green-600",
    "scss": "color(green, 600)",
    "type": "color",
    "value": "#28bd8b"
  },
  {
    "category": "background-color",
    "css": "--color-green-500",
    "friendly": "Color Green 500",
    "javascript": "color_green_500",
    "name": "color-green-500",
    "scss": "color(green, 500)",
    "type": "color",
    "value": "#52d9ac"
  },
  {
    "category": "background-color",
    "css": "--color-green-400",
    "friendly": "Color Green 400",
    "javascript": "color_green_400",
    "name": "color-green-400",
    "scss": "color(green, 400)",
    "type": "color",
    "value": "#8debcb"
  },
  {
    "category": "background-color",
    "css": "--color-green-300",
    "friendly": "Color Green 300",
    "javascript": "color_green_300",
    "name": "color-green-300",
    "scss": "color(green, 300)",
    "type": "color",
    "value": "#b5f5e0"
  },
  {
    "category": "background-color",
    "css": "--color-green-200",
    "friendly": "Color Green 200",
    "javascript": "color_green_200",
    "name": "color-green-200",
    "scss": "color(green, 200)",
    "type": "color",
    "value": "#d6fff1"
  },
  {
    "category": "background-color",
    "css": "--color-green-100",
    "friendly": "Color Green 100",
    "javascript": "color_green_100",
    "name": "color-green-100",
    "scss": "color(green, 100)",
    "type": "color",
    "value": "#e8fff7"
  },
  {
    "category": "background-color",
    "css": "--color-green-base",
    "friendly": "Color Green",
    "javascript": "color_green",
    "name": "color-green-base",
    "scss": "color(green)",
    "type": "color",
    "value": "#009f6a"
  },
  {
    "category": "background-color",
    "css": "--color-teal-1000",
    "friendly": "Color Teal 1000",
    "javascript": "color_teal_1000",
    "name": "color-teal-1000",
    "scss": "color(teal, 1000)",
    "type": "color",
    "value": "#223a3b"
  },
  {
    "category": "background-color",
    "css": "--color-teal-900",
    "friendly": "Color Teal 900",
    "javascript": "color_teal_900",
    "name": "color-teal-900",
    "scss": "color(teal, 900)",
    "type": "color",
    "value": "#274c4d"
  },
  {
    "category": "background-color",
    "css": "--color-teal-800",
    "friendly": "Color Teal 800",
    "javascript": "color_teal_800",
    "name": "color-teal-800",
    "scss": "color(teal, 800)",
    "type": "color",
    "value": "#226363"
  },
  {
    "category": "background-color",
    "css": "--color-teal-700",
    "friendly": "Color Teal 700",
    "javascript": "color_teal_700",
    "name": "color-teal-700",
    "scss": "color(teal, 700)",
    "type": "color",
    "value": "#199091"
  },
  {
    "category": "background-color",
    "css": "--color-teal-600",
    "friendly": "Color Teal 600",
    "javascript": "color_teal_600",
    "name": "color-teal-600",
    "scss": "color(teal, 600)",
    "type": "color",
    "value": "#13bebf"
  },
  {
    "category": "background-color",
    "css": "--color-teal-500",
    "friendly": "Color Teal 500",
    "javascript": "color_teal_500",
    "name": "color-teal-500",
    "scss": "color(teal, 500)",
    "type": "color",
    "value": "#37e4e6"
  },
  {
    "category": "background-color",
    "css": "--color-teal-400",
    "friendly": "Color Teal 400",
    "javascript": "color_teal_400",
    "name": "color-teal-400",
    "scss": "color(teal, 400)",
    "type": "color",
    "value": "#6ef4f5"
  },
  {
    "category": "background-color",
    "css": "--color-teal-300",
    "friendly": "Color Teal 300",
    "javascript": "color_teal_300",
    "name": "color-teal-300",
    "scss": "color(teal, 300)",
    "type": "color",
    "value": "#96feff"
  },
  {
    "category": "background-color",
    "css": "--color-teal-200",
    "friendly": "Color Teal 200",
    "javascript": "color_teal_200",
    "name": "color-teal-200",
    "scss": "color(teal, 200)",
    "type": "color",
    "value": "#ccffff"
  },
  {
    "category": "background-color",
    "css": "--color-teal-100",
    "friendly": "Color Teal 100",
    "javascript": "color_teal_100",
    "name": "color-teal-100",
    "scss": "color(teal, 100)",
    "type": "color",
    "value": "#e3ffff"
  },
  {
    "category": "background-color",
    "css": "--color-teal-base",
    "friendly": "Color Teal",
    "javascript": "color_teal",
    "name": "color-teal-base",
    "scss": "color(teal)",
    "type": "color",
    "value": "#37e4e6"
  },
  {
    "category": "background-color",
    "css": "--color-blue-1000",
    "friendly": "Color Blue 1000",
    "javascript": "color_blue_1000",
    "name": "color-blue-1000",
    "scss": "color(blue, 1000)",
    "type": "color",
    "value": "#203752"
  },
  {
    "category": "background-color",
    "css": "--color-blue-900",
    "friendly": "Color Blue 900",
    "javascript": "color_blue_900",
    "name": "color-blue-900",
    "scss": "color(blue, 900)",
    "type": "color",
    "value": "#1a497d"
  },
  {
    "category": "background-color",
    "css": "--color-blue-800",
    "friendly": "Color Blue 800",
    "javascript": "color_blue_800",
    "name": "color-blue-800",
    "scss": "color(blue, 800)",
    "type": "color",
    "value": "#0060cc"
  },
  {
    "category": "background-color",
    "css": "--color-blue-700",
    "friendly": "Color Blue 700",
    "javascript": "color_blue_700",
    "name": "color-blue-700",
    "scss": "color(blue, 700)",
    "type": "color",
    "value": "#0578ff"
  },
  {
    "category": "background-color",
    "css": "--color-blue-600",
    "friendly": "Color Blue 600",
    "javascript": "color_blue_600",
    "name": "color-blue-600",
    "scss": "color(blue, 600)",
    "type": "color",
    "value": "#429bff"
  },
  {
    "category": "background-color",
    "css": "--color-blue-500",
    "friendly": "Color Blue 500",
    "javascript": "color_blue_500",
    "name": "color-blue-500",
    "scss": "color(blue, 500)",
    "type": "color",
    "value": "#78b6ff"
  },
  {
    "category": "background-color",
    "css": "--color-blue-400",
    "friendly": "Color Blue 400",
    "javascript": "color_blue_400",
    "name": "color-blue-400",
    "scss": "color(blue, 400)",
    "type": "color",
    "value": "#abd2ff"
  },
  {
    "category": "background-color",
    "css": "--color-blue-300",
    "friendly": "Color Blue 300",
    "javascript": "color_blue_300",
    "name": "color-blue-300",
    "scss": "color(blue, 300)",
    "type": "color",
    "value": "#cce3ff"
  },
  {
    "category": "background-color",
    "css": "--color-blue-200",
    "friendly": "Color Blue 200",
    "javascript": "color_blue_200",
    "name": "color-blue-200",
    "scss": "color(blue, 200)",
    "type": "color",
    "value": "#e8f3ff"
  },
  {
    "category": "background-color",
    "css": "--color-blue-100",
    "friendly": "Color Blue 100",
    "javascript": "color_blue_100",
    "name": "color-blue-100",
    "scss": "color(blue, 100)",
    "type": "color",
    "value": "#f2f8ff"
  },
  {
    "category": "background-color",
    "css": "--color-blue-base",
    "friendly": "Color Blue",
    "javascript": "color_blue",
    "name": "color-blue-base",
    "scss": "color(blue)",
    "type": "color",
    "value": "#0578ff"
  },
  {
    "category": "background-color",
    "css": "--color-purple-1000",
    "friendly": "Color Purple 1000",
    "javascript": "color_purple_1000",
    "name": "color-purple-1000",
    "scss": "color(purple, 1000)",
    "type": "color",
    "value": "#352e4a"
  },
  {
    "category": "background-color",
    "css": "--color-purple-900",
    "friendly": "Color Purple 900",
    "javascript": "color_purple_900",
    "name": "color-purple-900",
    "scss": "color(purple, 900)",
    "type": "color",
    "value": "#4c2e87"
  },
  {
    "category": "background-color",
    "css": "--color-purple-800",
    "friendly": "Color Purple 800",
    "javascript": "color_purple_800",
    "name": "color-purple-800",
    "scss": "color(purple, 800)",
    "type": "color",
    "value": "#7122e3"
  },
  {
    "category": "background-color",
    "css": "--color-purple-700",
    "friendly": "Color Purple 700",
    "javascript": "color_purple_700",
    "name": "color-purple-700",
    "scss": "color(purple, 700)",
    "type": "color",
    "value": "#8c40ff"
  },
  {
    "category": "background-color",
    "css": "--color-purple-600",
    "friendly": "Color Purple 600",
    "javascript": "color_purple_600",
    "name": "color-purple-600",
    "scss": "color(purple, 600)",
    "type": "color",
    "value": "#a469ff"
  },
  {
    "category": "background-color",
    "css": "--color-purple-500",
    "friendly": "Color Purple 500",
    "javascript": "color_purple_500",
    "name": "color-purple-500",
    "scss": "color(purple, 500)",
    "type": "color",
    "value": "#bd91ff"
  },
  {
    "category": "background-color",
    "css": "--color-purple-400",
    "friendly": "Color Purple 400",
    "javascript": "color_purple_400",
    "name": "color-purple-400",
    "scss": "color(purple, 400)",
    "type": "color",
    "value": "#d7bdff"
  },
  {
    "category": "background-color",
    "css": "--color-purple-300",
    "friendly": "Color Purple 300",
    "javascript": "color_purple_300",
    "name": "color-purple-300",
    "scss": "color(purple, 300)",
    "type": "color",
    "value": "#e5d4ff"
  },
  {
    "category": "background-color",
    "css": "--color-purple-200",
    "friendly": "Color Purple 200",
    "javascript": "color_purple_200",
    "name": "color-purple-200",
    "scss": "color(purple, 200)",
    "type": "color",
    "value": "#f3ebff"
  },
  {
    "category": "background-color",
    "css": "--color-purple-100",
    "friendly": "Color Purple 100",
    "javascript": "color_purple_100",
    "name": "color-purple-100",
    "scss": "color(purple, 100)",
    "type": "color",
    "value": "#f9f5ff"
  },
  {
    "category": "background-color",
    "css": "--color-purple-base",
    "friendly": "Color Purple",
    "javascript": "color_purple",
    "name": "color-purple-base",
    "scss": "color(purple)",
    "type": "color",
    "value": "#8c40ff"
  },
  {
    "category": "background-color",
    "css": "--color-magenta-1000",
    "friendly": "Color Magenta 1000",
    "javascript": "color_magenta_1000",
    "name": "color-magenta-1000",
    "scss": "color(magenta, 1000)",
    "type": "color",
    "value": "#522338"
  },
  {
    "category": "background-color",
    "css": "--color-magenta-900",
    "friendly": "Color Magenta 900",
    "javascript": "color_magenta_900",
    "name": "color-magenta-900",
    "scss": "color(magenta, 900)",
    "type": "color",
    "value": "#782449"
  },
  {
    "category": "background-color",
    "css": "--color-magenta-800",
    "friendly": "Color Magenta 800",
    "javascript": "color_magenta_800",
    "name": "color-magenta-800",
    "scss": "color(magenta, 800)",
    "type": "color",
    "value": "#992659"
  },
  {
    "category": "background-color",
    "css": "--color-magenta-700",
    "friendly": "Color Magenta 700",
    "javascript": "color_magenta_700",
    "name": "color-magenta-700",
    "scss": "color(magenta, 700)",
    "type": "color",
    "value": "#d1347a"
  },
  {
    "category": "background-color",
    "css": "--color-magenta-600",
    "friendly": "Color Magenta 600",
    "javascript": "color_magenta_600",
    "name": "color-magenta-600",
    "scss": "color(magenta, 600)",
    "type": "color",
    "value": "#f0549a"
  },
  {
    "category": "background-color",
    "css": "--color-magenta-500",
    "friendly": "Color Magenta 500",
    "javascript": "color_magenta_500",
    "name": "color-magenta-500",
    "scss": "color(magenta, 500)",
    "type": "color",
    "value": "#ff7db7"
  },
  {
    "category": "background-color",
    "css": "--color-magenta-400",
    "friendly": "Color Magenta 400",
    "javascript": "color_magenta_400",
    "name": "color-magenta-400",
    "scss": "color(magenta, 400)",
    "type": "color",
    "value": "#ffb0d3"
  },
  {
    "category": "background-color",
    "css": "--color-magenta-300",
    "friendly": "Color Magenta 300",
    "javascript": "color_magenta_300",
    "name": "color-magenta-300",
    "scss": "color(magenta, 300)",
    "type": "color",
    "value": "#ffcce3"
  },
  {
    "category": "background-color",
    "css": "--color-magenta-200",
    "friendly": "Color Magenta 200",
    "javascript": "color_magenta_200",
    "name": "color-magenta-200",
    "scss": "color(magenta, 200)",
    "type": "color",
    "value": "#ffe8f2"
  },
  {
    "category": "background-color",
    "css": "--color-magenta-100",
    "friendly": "Color Magenta 100",
    "javascript": "color_magenta_100",
    "name": "color-magenta-100",
    "scss": "color(magenta, 100)",
    "type": "color",
    "value": "#fff2f8"
  },
  {
    "category": "background-color",
    "css": "--color-magenta-base",
    "friendly": "Color Magenta",
    "javascript": "color_magenta",
    "name": "color-magenta-base",
    "scss": "color(magenta)",
    "type": "color",
    "value": "#d1347a"
  },
  {
    "category": "background-color",
    "css": "--color-red-1000",
    "friendly": "Color Red 1000",
    "javascript": "color_red_1000",
    "name": "color-red-1000",
    "scss": "color(red, 1000)",
    "type": "color",
    "value": "#5c2121"
  },
  {
    "category": "background-color",
    "css": "--color-red-900",
    "friendly": "Color Red 900",
    "javascript": "color_red_900",
    "name": "color-red-900",
    "scss": "color(red, 900)",
    "type": "color",
    "value": "#80252a"
  },
  {
    "category": "background-color",
    "css": "--color-red-800",
    "friendly": "Color Red 800",
    "javascript": "color_red_800",
    "name": "color-red-800",
    "scss": "color(red, 800)",
    "type": "color",
    "value": "#a12b2b"
  },
  {
    "category": "background-color",
    "css": "--color-red-700",
    "friendly": "Color Red 700",
    "javascript": "color_red_700",
    "name": "color-red-700",
    "scss": "color(red, 700)",
    "type": "color",
    "value": "#d9363e"
  },
  {
    "category": "background-color",
    "css": "--color-red-600",
    "friendly": "Color Red 600",
    "javascript": "color_red_600",
    "name": "color-red-600",
    "scss": "color(red, 600)",
    "type": "color",
    "value": "#ff5760"
  },
  {
    "category": "background-color",
    "css": "--color-red-500",
    "friendly": "Color Red 500",
    "javascript": "color_red_500",
    "name": "color-red-500",
    "scss": "color(red, 500)",
    "type": "color",
    "value": "#ff858b"
  },
  {
    "category": "background-color",
    "css": "--color-red-400",
    "friendly": "Color Red 400",
    "javascript": "color_red_400",
    "name": "color-red-400",
    "scss": "color(red, 400)",
    "type": "color",
    "value": "#ffb5b9"
  },
  {
    "category": "background-color",
    "css": "--color-red-300",
    "friendly": "Color Red 300",
    "javascript": "color_red_300",
    "name": "color-red-300",
    "scss": "color(red, 300)",
    "type": "color",
    "value": "#ffcfd1"
  },
  {
    "category": "background-color",
    "css": "--color-red-200",
    "friendly": "Color Red 200",
    "javascript": "color_red_200",
    "name": "color-red-200",
    "scss": "color(red, 200)",
    "type": "color",
    "value": "#ffebec"
  },
  {
    "category": "background-color",
    "css": "--color-red-100",
    "friendly": "Color Red 100",
    "javascript": "color_red_100",
    "name": "color-red-100",
    "scss": "color(red, 100)",
    "type": "color",
    "value": "#fff2f3"
  },
  {
    "category": "background-color",
    "css": "--color-red-base",
    "friendly": "Color Red",
    "javascript": "color_red",
    "name": "color-red-base",
    "scss": "color(red)",
    "type": "color",
    "value": "#d9363e"
  },
  {
    "category": "background-color",
    "css": "--color-gray-1000",
    "friendly": "Color Gray 1000",
    "javascript": "color_gray_1000",
    "name": "color-gray-1000",
    "scss": "color(gray, 1000)",
    "type": "color",
    "value": "#2c353d"
  },
  {
    "category": "background-color",
    "css": "--color-gray-900",
    "friendly": "Color Gray 900",
    "javascript": "color_gray_900",
    "name": "color-gray-900",
    "scss": "color(gray, 900)",
    "type": "color",
    "value": "#39444d"
  },
  {
    "category": "background-color",
    "css": "--color-gray-800",
    "friendly": "Color Gray 800",
    "javascript": "color_gray_800",
    "name": "color-gray-800",
    "scss": "color(gray, 800)",
    "type": "color",
    "value": "#46525c"
  },
  {
    "category": "background-color",
    "css": "--color-gray-700",
    "friendly": "Color Gray 700",
    "javascript": "color_gray_700",
    "name": "color-gray-700",
    "scss": "color(gray, 700)",
    "type": "color",
    "value": "#626f7a"
  },
  {
    "category": "background-color",
    "css": "--color-gray-600",
    "friendly": "Color Gray 600",
    "javascript": "color_gray_600",
    "name": "color-gray-600",
    "scss": "color(gray, 600)",
    "type": "color",
    "value": "#818e9a"
  },
  {
    "category": "background-color",
    "css": "--color-gray-500",
    "friendly": "Color Gray 500",
    "javascript": "color_gray_500",
    "name": "color-gray-500",
    "scss": "color(gray, 500)",
    "type": "color",
    "value": "#a2adb8"
  },
  {
    "category": "background-color",
    "css": "--color-gray-400",
    "friendly": "Color Gray 400",
    "javascript": "color_gray_400",
    "name": "color-gray-400",
    "scss": "color(gray, 400)",
    "type": "color",
    "value": "#c5ced6"
  },
  {
    "category": "background-color",
    "css": "--color-gray-300",
    "friendly": "Color Gray 300",
    "javascript": "color_gray_300",
    "name": "color-gray-300",
    "scss": "color(gray, 300)",
    "type": "color",
    "value": "#d9e0e6"
  },
  {
    "category": "background-color",
    "css": "--color-gray-200",
    "friendly": "Color Gray 200",
    "javascript": "color_gray_200",
    "name": "color-gray-200",
    "scss": "color(gray, 200)",
    "type": "color",
    "value": "#ebf0f5"
  },
  {
    "category": "background-color",
    "css": "--color-gray-100",
    "friendly": "Color Gray 100",
    "javascript": "color_gray_100",
    "name": "color-gray-100",
    "scss": "color(gray, 100)",
    "type": "color",
    "value": "#f5f8fa"
  },
  {
    "category": "background-color",
    "css": "--color-gray-base",
    "friendly": "Color Gray",
    "javascript": "color_gray",
    "name": "color-gray-base",
    "scss": "color(gray)",
    "type": "color",
    "value": "#818e9a"
  },
  {
    "category": "background-color",
    "css": "--color-white-base",
    "friendly": "Color White",
    "javascript": "color_white",
    "name": "color-white-base",
    "scss": "color(white)",
    "type": "color",
    "value": "#ffffff"
  },
  {
    "category": "font-family",
    "css": "--font-family-base",
    "friendly": "Font Family Default",
    "javascript": "fontfamily",
    "name": "font-family-base",
    "scss": "font-family()",
    "type": "font-family",
    "value": "'Calibre', -apple-system, BlinkMacSystemFont, 'San Francisco', 'Segoe UI', Roboto, Helvetica, sans-serif"
  },
  {
    "category": "font-family",
    "css": "--font-family-monospace",
    "friendly": "Font Family Monospace",
    "javascript": "fontfamily_monospace",
    "name": "font-family-monospace",
    "scss": "font-family(monospace)",
    "type": "font-family",
    "value": "'SFMono-Regular', Monaco, Consolas, 'Lucida Console', monospace"
  },
  {
    "category": "font-size",
    "css": "--font-size-800",
    "friendly": "Font Size 800",
    "javascript": "fontsize_800",
    "name": "font-size-800",
    "scss": "font-size(800)",
    "type": "font-size",
    "value": "3.5rem",
    "pixel_value": "56px"
  },
  {
    "category": "font-size",
    "css": "--font-size-700",
    "friendly": "Font Size 700",
    "javascript": "fontsize_700",
    "name": "font-size-700",
    "scss": "font-size(700)",
    "type": "font-size",
    "value": "2.75rem",
    "pixel_value": "44px"
  },
  {
    "category": "font-size",
    "css": "--font-size-600",
    "friendly": "Font Size 600",
    "javascript": "fontsize_600",
    "name": "font-size-600",
    "scss": "font-size(600)",
    "type": "font-size",
    "value": "2rem",
    "pixel_value": "32px"
  },
  {
    "category": "font-size",
    "css": "--font-size-500",
    "friendly": "Font Size 500",
    "javascript": "fontsize_500",
    "name": "font-size-500",
    "scss": "font-size(500)",
    "type": "font-size",
    "value": "1.5rem",
    "pixel_value": "24px"
  },
  {
    "category": "font-size",
    "css": "--font-size-400",
    "friendly": "Font Size 400",
    "javascript": "fontsize_400",
    "name": "font-size-400",
    "scss": "font-size(400)",
    "type": "font-size",
    "value": "1.25rem",
    "pixel_value": "20px"
  },
  {
    "category": "font-size",
    "css": "--font-size-300",
    "friendly": "Font Size 300",
    "javascript": "fontsize_300",
    "name": "font-size-300",
    "scss": "font-size(300)",
    "type": "font-size",
    "value": "1.125rem",
    "pixel_value": "18px"
  },
  {
    "category": "font-size",
    "css": "--font-size-200",
    "friendly": "Font Size 200",
    "javascript": "fontsize_200",
    "name": "font-size-200",
    "scss": "font-size(200)",
    "type": "font-size",
    "value": "1rem",
    "pixel_value": "16px"
  },
  {
    "category": "font-size",
    "css": "--font-size-100",
    "friendly": "Font Size 100",
    "javascript": "fontsize_100",
    "name": "font-size-100",
    "scss": "font-size(100)",
    "type": "font-size",
    "value": "0.875rem",
    "pixel_value": "14px"
  },
  {
    "category": "font-size",
    "css": "--font-size-base",
    "friendly": "Font Size Default",
    "javascript": "fontsize",
    "name": "font-size-base",
    "scss": "font-size()",
    "type": "font-size",
    "value": "1.125rem",
    "pixel_value": "18px"
  },
  {
    "category": "line-height",
    "css": "--line-height-800",
    "friendly": "Line Height 800",
    "javascript": "lineheight_800",
    "name": "line-height-800",
    "scss": "line-height(800)",
    "type": "line-height",
    "value": "4.25rem",
    "pixel_value": "68px"
  },
  {
    "category": "line-height",
    "css": "--line-height-700",
    "friendly": "Line Height 700",
    "javascript": "lineheight_700",
    "name": "line-height-700",
    "scss": "line-height(700)",
    "type": "line-height",
    "value": "3.5rem",
    "pixel_value": "56px"
  },
  {
    "category": "line-height",
    "css": "--line-height-600",
    "friendly": "Line Height 600",
    "javascript": "lineheight_600",
    "name": "line-height-600",
    "scss": "line-height(600)",
    "type": "line-height",
    "value": "2.5rem",
    "pixel_value": "40px"
  },
  {
    "category": "line-height",
    "css": "--line-height-500",
    "friendly": "Line Height 500",
    "javascript": "lineheight_500",
    "name": "line-height-500",
    "scss": "line-height(500)",
    "type": "line-height",
    "value": "2rem",
    "pixel_value": "32px"
  },
  {
    "category": "line-height",
    "css": "--line-height-400",
    "friendly": "Line Height 400",
    "javascript": "lineheight_400",
    "name": "line-height-400",
    "scss": "line-height(400)",
    "type": "line-height",
    "value": "1.750rem",
    "pixel_value": "28px"
  },
  {
    "category": "line-height",
    "css": "--line-height-300",
    "friendly": "Line Height 300",
    "javascript": "lineheight_300",
    "name": "line-height-300",
    "scss": "line-height(300)",
    "type": "line-height",
    "value": "1.5rem",
    "pixel_value": "24px"
  },
  {
    "category": "line-height",
    "css": "--line-height-200",
    "friendly": "Line Height 200",
    "javascript": "lineheight_200",
    "name": "line-height-200",
    "scss": "line-height(200)",
    "type": "line-height",
    "value": "1.25rem",
    "pixel_value": "20px"
  },
  {
    "category": "line-height",
    "css": "--line-height-100",
    "friendly": "Line Height 100",
    "javascript": "lineheight_100",
    "name": "line-height-100",
    "scss": "line-height(100)",
    "type": "line-height",
    "value": "1rem",
    "pixel_value": "16px"
  },
  {
    "category": "line-height",
    "css": "--line-height-base",
    "friendly": "Line Height Default",
    "javascript": "lineheight",
    "name": "line-height-base",
    "scss": "line-height()",
    "type": "line-height",
    "value": "1.5rem",
    "pixel_value": "24px"
  },
  {
    "category": "spacing",
    "css": "--spacing-800",
    "friendly": "Spacing 800",
    "javascript": "spacing_800",
    "name": "spacing-800",
    "scss": "spacing(800)",
    "type": "spacing",
    "value": "4rem",
    "pixel_value": "64px"
  },
  {
    "category": "spacing",
    "css": "--spacing-700",
    "friendly": "Spacing 700",
    "javascript": "spacing_700",
    "name": "spacing-700",
    "scss": "spacing(700)",
    "type": "spacing",
    "value": "3rem",
    "pixel_value": "48px"
  },
  {
    "category": "spacing",
    "css": "--spacing-600",
    "friendly": "Spacing 600",
    "javascript": "spacing_600",
    "name": "spacing-600",
    "scss": "spacing(600)",
    "type": "spacing",
    "value": "2rem",
    "pixel_value": "32px"
  },
  {
    "category": "spacing",
    "css": "--spacing-500",
    "friendly": "Spacing 500",
    "javascript": "spacing_500",
    "name": "spacing-500",
    "scss": "spacing(500)",
    "type": "spacing",
    "value": "1.5rem",
    "pixel_value": "24px"
  },
  {
    "category": "spacing",
    "css": "--spacing-400",
    "friendly": "Spacing 400",
    "javascript": "spacing_400",
    "name": "spacing-400",
    "scss": "spacing(400)",
    "type": "spacing",
    "value": "1rem",
    "pixel_value": "16px"
  },
  {
    "category": "spacing",
    "css": "--spacing-300",
    "friendly": "Spacing 300",
    "javascript": "spacing_300",
    "name": "spacing-300",
    "scss": "spacing(300)",
    "type": "spacing",
    "value": "0.75rem",
    "pixel_value": "12px"
  },
  {
    "category": "spacing",
    "css": "--spacing-200",
    "friendly": "Spacing 200",
    "javascript": "spacing_200",
    "name": "spacing-200",
    "scss": "spacing(200)",
    "type": "spacing",
    "value": "0.5rem",
    "pixel_value": "8px"
  },
  {
    "category": "spacing",
    "css": "--spacing-100",
    "friendly": "Spacing 100",
    "javascript": "spacing_100",
    "name": "spacing-100",
    "scss": "spacing(100)",
    "type": "spacing",
    "value": "0.25rem",
    "pixel_value": "4px"
  },
  {
    "category": "spacing",
    "css": "--spacing-0",
    "friendly": "Spacing 0",
    "javascript": "spacing_0",
    "name": "spacing-0",
    "scss": "spacing(0)",
    "type": "spacing",
    "value": "0rem",
    "pixel_value": "0px"
  },
  {
    "category": "spacing",
    "css": "--spacing-base",
    "friendly": "Spacing Default",
    "javascript": "spacing",
    "name": "spacing-base",
    "scss": "spacing()",
    "type": "spacing",
    "value": "1rem",
    "pixel_value": "16px"
  }
]
