import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, UnstyledLink, InlineCode } from '@sparkpost/matchbox';

const Home: NextPage = () => {
  return (
    <Box height="100vh" display="flex" alignItems="center" justifyContent="center" textAlign="center" fontFamily="sans">
      <Head>
        <title>Next Template Matchbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main>
        <Box as="h1" color="gray.900">
          SparkPost <UnstyledLink to="https://nextjs.org" external>Next.js!</UnstyledLink> Template
        </Box>
        <Box as="h2" color="gray.700" mt="200" fontWeight="light">
          Edit <InlineCode>index.tsx</InlineCode> to get started.
        </Box>
      </main>
    </Box>
  )
}

export default Home
