name: 'Label PR'
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
