name: Visual Regression Tests

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Prepare tests
        run: npm run pretest:ci
      - name: Visual Regression tests
        run: npm run test:regression:ci
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
