name: Unit and end-to-end testing

on: [pull_request]

jobs:
  testing:
    runs-on: ubuntu-16.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Testing
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: npm run test:ci
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Cypress Videos
          path: /home/runner/work/matchbox/matchbox/cypress/videos/
