name: Unit and Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-16.04
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Prepare tests
        run: npm run pretest:ci
      - name: Unit tests
        run: npm run test:unit:ci
      - name: E2E tests
        run: npm run test:e2e:ci
      - name: Prepare coverage
        run: npm run coverage:all
      - name: Report to Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          file: ./coverage/lcov.info
