# This workflow will do a clean install of node dependencies on the website and run its build
name: Build

on: [pull_request]

jobs:
  all:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd packages/matchbox-website
      - run: npm ci
      - run: npm run build --if-present
